rootProject.name = "Rick and Morty Compose"
include(":app")
include(":graphql")
include(":apollo")
include(":room")
include(":data-store")
include(":domain")
include(":common-test")
include(":common-util")
include(":common-ui")
include(":navigation")
include(":collapsable-drawer")
include(":snackbar")
include(":character-all")
include(":episode-all")
