rootProject.name = "Rick and Morty Compose"

include(":app")
include(":graphql")
include(":apollo")
include(":room")
include(":data-store")
include(":domain")
include(":common-test")
include(":common-util")
include(":common-ui")
include(":navigation")
include(":collapsable-drawer")
include(":snackbar")
include(":drawer")
include(":theme-controller")
include(":character-common")
include(":character-all")
include(":character-favorite")
include(":character-details")
include(":episode-common")
include(":episode-all")
include(":episode-favorite")
include(":episode-details")
include(":location-common")
include(":location-all")
include(":location-favorite")
include(":location-details")
