object Module {
    const val app = ":app"
    const val apollo = ":apollo"
    const val graphql = ":graphql"
    const val room = ":room"
    const val dataStore = ":data-store"
    const val domain = ":domain"
    const val commonTest = ":common-test"
    const val commonUtil = ":common-util"
    const val commonUi = ":common-ui"
    const val navigation = ":navigation"
    const val collapsableDrawer = ":collapsable-drawer"
    const val characterAll = ":character-all"
    const val characterFavorite = ":character-favorite"
    const val characterDetails = ":character-details"
    const val episodeAll = ":episode-all"
    const val episodeFavorite = ":episode-favorite"
    const val episodeDetails = ":episode-details"
    const val locationAll = ":location-all"
    const val locationFavorite = ":location-favorite"
    const val locationDetails = ":location-details"
    const val snackbar = ":snackbar"
}
