name: PR

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
      - '*.yml'
    branches: [ main ]
  workflow_dispatch:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run Detekt
        run: ./gradlew detekt

  test:
    needs: [ detekt ]
    strategy:
      matrix:
        module: [ room, apollo, graphql, data-store, domain, app ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/${{ matrix.module }}/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run Tests
        run: ./gradlew :${{ matrix.module }}:check --stacktrace
